// Object IDs for the objects in the object pool.
#define NULL_OBJECT 65535
#define WORKING_SET 1
#define GRAPHIC_LOGO 2
#define PLACEHOLDER_DATA_MASK 3
#define AUXN_INPUT_SLIDER 3000
#define AUXN_INPUT_SLIDER_GRAPHIC 3001
#define AUXN_INPUT_BUTTON 3020
#define AUXN_INPUT_BUTTON_GRAPHIC 3021
