// Object IDs for the objects in the object pool.
#define NULL_OBJECT 65535
#define WORKING_SET 1
#define GRAPHIC_LOGO 2
#define PLACEHOLDER_DATA_MASK 3
#define AUXN_FUNCTION_ONOFF 10000
#define AUNX_FUNCTION_ONOFF_GRAPHIC 10001
#define AUXN_FUNCTION_PLUS 10020
#define AUXN_FUNCTION_PLUS_GRAPHIC 10021
