name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        example: [examples/virtual_terminal/esp32_platformio_object_pool]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Install AgIsoStack library in PlatformIO
        run: pio pkg install -g -l ./
      - name: Build PlatformIO examples
        run: pio run -d ${{ matrix.example }} -e local_agisostack
